version: "3.9"

services:
    go:
      # container_name: go
      image: go
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
      links:
        - db
      environment:
        host: db
        port: 3306
        user: root
        password: root
        dbname: teachers
        secret: ciao
      ports:
        - "8080:8080"
      networks:
        - "teacher"
      # deploy:
      #   replicas: 3
    db:
      image: mysql
      restart: always
      environment:
        MYSQL_DATABASE: teachers
        MYSQL_USER: vano
        MYSQL_PASSWORD: vano
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306"
      # expose:
      #   - 3306
      volumes:
        - ./db-dump:/var/lib/mysql
      networks:
        - "teacher"
    # nginx container
    # nginx:
    #   # specifies the latest nginx image
    #   image: nginx:latest
    #   # Connects the conf file of the container to the conf file in our folder
    #   volumes:
    #       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #   # It will start up the nginx only when all api containers have started
    #   depends_on: 
    #     - go
    #   # Connects the port 80 of the nginx container to localhost:80 or localhost
    #   ports: 
    #     - "80:80"
    #   networks: 
    #     - "blobber"
volumes:
  db:

networks:
  teacher: